# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85d584a8f26fa08accd5f667b1995f48e8eedd54df57a141ef027357827d1c69e6ccdf1b45870635f1ef8cd9199acaf3d24c36b784a67a353390b7575d626f6a

test:
  secret_key_base: fe84e666006b1d7996b73b8ac53ad4bd374ebc320385a28e1968c78403068a42f162987b4cb80752d37862f935ef7ba9d2fcd68faf491160cd7aa45997b3d553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
